//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace TWMVC.Models
{
    public partial class NorthwindEntities : ObjectContext
    {
        public const string ConnectionString = "name=NorthwindEntities";
        public const string ContainerName = "NorthwindEntities";
    
        #region Constructors
    
        public NorthwindEntities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public NorthwindEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public NorthwindEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // 建立 Proxy 時需要用到 ProxyDataContractResolver 和
            // 可允許消極式載入，這種載入可以在序列化期間擴充載入的圖形。
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet 屬性
    
        public ObjectSet<Categories> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Categories>("Categories")); }
        }
        private ObjectSet<Categories> _categories;
    
        public ObjectSet<CustomerDemographics> CustomerDemographics
        {
            get { return _customerDemographics  ?? (_customerDemographics = CreateObjectSet<CustomerDemographics>("CustomerDemographics")); }
        }
        private ObjectSet<CustomerDemographics> _customerDemographics;
    
        public ObjectSet<Customers> Customers
        {
            get { return _customers  ?? (_customers = CreateObjectSet<Customers>("Customers")); }
        }
        private ObjectSet<Customers> _customers;
    
        public ObjectSet<Employees> Employees
        {
            get { return _employees  ?? (_employees = CreateObjectSet<Employees>("Employees")); }
        }
        private ObjectSet<Employees> _employees;
    
        public ObjectSet<LargeEmployees> LargeEmployees
        {
            get { return _largeEmployees  ?? (_largeEmployees = CreateObjectSet<LargeEmployees>("LargeEmployees")); }
        }
        private ObjectSet<LargeEmployees> _largeEmployees;
    
        public ObjectSet<Order_Details> Order_Details
        {
            get { return _order_Details  ?? (_order_Details = CreateObjectSet<Order_Details>("Order_Details")); }
        }
        private ObjectSet<Order_Details> _order_Details;
    
        public ObjectSet<Orders> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Orders>("Orders")); }
        }
        private ObjectSet<Orders> _orders;
    
        public ObjectSet<Products> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Products>("Products")); }
        }
        private ObjectSet<Products> _products;
    
        public ObjectSet<Region> Region
        {
            get { return _region  ?? (_region = CreateObjectSet<Region>("Region")); }
        }
        private ObjectSet<Region> _region;
    
        public ObjectSet<Shippers> Shippers
        {
            get { return _shippers  ?? (_shippers = CreateObjectSet<Shippers>("Shippers")); }
        }
        private ObjectSet<Shippers> _shippers;
    
        public ObjectSet<Suppliers> Suppliers
        {
            get { return _suppliers  ?? (_suppliers = CreateObjectSet<Suppliers>("Suppliers")); }
        }
        private ObjectSet<Suppliers> _suppliers;
    
        public ObjectSet<Territories> Territories
        {
            get { return _territories  ?? (_territories = CreateObjectSet<Territories>("Territories")); }
        }
        private ObjectSet<Territories> _territories;

        #endregion
    }
}
